---
name: Net-BitTorrent
version: 0.049_003
author:
  - 'Sanko Robinson <sanko@cpan.org>'
abstract: BitTorrent peer-to-peer protocol
license: artistic_2
resources:
  ChangeLog: http://github.com/sanko/net-bittorrent/commits/master
  MailingList: http://groups.google.com/group/net-bittorrent
  bugtracker: http://code.google.com/p/net-bittorrent/issues/list
  homepage: http://sankorobinson.com/net-bittorrent/
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: http://github.com/sanko/net-bittorrent/
requires:
  Cwd: 0
  Digest::SHA: 5.45
  Errno: 0
  Exporter: 0
  Fcntl: 0
  File::Path: 0
  File::Spec: 0
  Math::BigInt: 0
  Module::Build: 0.3
  Scalar::Util: 1.19
  Socket: 1.77
  Test::More: 0.8
  Time::HiRes: 0
  perl: 5.8.1
  version: 0.74
build_requires:
  Module::Build: 0.3
  Test::More: 0.8
recommends:
  Data::Dump: 0
provides:
  Net::BitTorrent:
    file: lib/Net/BitTorrent.pm
    version: 0.049_003
  Net::BitTorrent::DHT:
    file: lib/Net/BitTorrent/DHT.pm
    version: 0.049_002
  Net::BitTorrent::Peer:
    file: lib/Net/BitTorrent/Peer.pm
    version: 0.049_004
  Net::BitTorrent::Protocol:
    file: lib/Net/BitTorrent/Protocol.pm
    version: 0.048_002
  Net::BitTorrent::Torrent:
    file: lib/Net/BitTorrent/Torrent.pm
    version: 0.049_004
  Net::BitTorrent::Torrent::File:
    file: lib/Net/BitTorrent/Torrent/File.pm
    version: 0.042_002
  Net::BitTorrent::Torrent::Tracker:
    file: lib/Net/BitTorrent/Torrent/Tracker.pm
    version: 0.049_003
  Net::BitTorrent::Torrent::Tracker::HTTP:
    file: lib/Net/BitTorrent/Torrent/Tracker/HTTP.pm
    version: 0.049_003
  Net::BitTorrent::Torrent::Tracker::UDP:
    file: lib/Net/BitTorrent/Torrent/Tracker/UDP.pm
    version: 0.049_003
  Net::BitTorrent::Util:
    file: lib/Net/BitTorrent/Util.pm
    version: 0.040_001
  Net::BitTorrent::Version:
    file: lib/Net/BitTorrent/Version.pm
    version: 0.049_003
generated_by: 'Conversion, software version 7.0'
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - BitTorrent
  - client
  - peer
  - p2p
  - torrent
  - socket
  - DHT
