---
name: Net-BitTorrent
version: 0.027_001
author:
  - 'Sanko Robinson <sanko@cpan.org>'
abstract: BitTorrent peer-to-peer protocol
license: artistic_2
resources:
  MailingList: http://groups.google.com/group/net-bittorrent-discuss
  bugtracker: http://code.google.com/p/net-bittorrent/issues/list
  homepage: http://sankorobinson.com/net-bittorrent/
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: http://net-bittorrent.googlecode.com/svn/trunk/
requires:
  Cwd: 0
  Digest::SHA: 5.45
  Errno: 0
  Exporter: 0
  Fcntl: 0
  File::Path: 0
  File::Spec: 0
  Module::Build: 0.2805
  Scalar::Util: 1.19
  Socket: 1.77
  Test::More: 0.72
  Time::HiRes: 0
  perl: 5.8.1
  version: 0.74
build_requires:
  Module::Build: 0.280801
  Test::More: 0.72
recommends:
  Data::Dumper: 0
  Encode: 0
  Win32: 0
  Win32API::File: 0.1
  perl: 5.8.7
  utf8: 0
provides:
  Net::BitTorrent:
    file: lib/Net/BitTorrent.pm
    version: 0.027_001
  Net::BitTorrent::DHT:
    file: lib/Net/BitTorrent/DHT.pm
    version: 0.027
  Net::BitTorrent::DHT::Node:
    file: lib/Net/BitTorrent/DHT/Node.pm
    version: 0.027
  Net::BitTorrent::Peer:
    file: lib/Net/BitTorrent/Peer.pm
    version: 0.027
  Net::BitTorrent::Protocol:
    file: lib/Net/BitTorrent/Protocol.pm
    version: 0.027
  Net::BitTorrent::Session:
    file: lib/Net/BitTorrent/Session.pm
    version: 0.027
  Net::BitTorrent::Session::File:
    file: lib/Net/BitTorrent/Session/File.pm
    version: 0.027
  Net::BitTorrent::Session::Tracker:
    file: lib/Net/BitTorrent/Session/Tracker.pm
    version: 0.027
  Net::BitTorrent::Session::Tracker::HTTP:
    file: lib/Net/BitTorrent/Session/Tracker/HTTP.pm
    version: 0.027
  Net::BitTorrent::Session::Tracker::UDP:
    file: lib/Net/BitTorrent/Session/Tracker/UDP.pm
    version: 0.027
  Net::BitTorrent::Util:
    file: lib/Net/BitTorrent/Util.pm
    version: 0.027
generated_by: 'Sanko Robinson <sanko@cpan.org>'
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - BitTorrent
  - client
  - peer
  - p2p
  - torrent
  - socket
  - dht
